# Projekt: 1
# Autor:   Michal Řezník
# Datum:   27.2.2022
SHELL = /usr/bin/env bash
NAME = proj1
LOGIN = xrezni28

all:
	pdflatex $(NAME).tex
	pdflatex $(NAME).tex

clean:
	rm -f $(NAME).{out,aux,dvi,log,pdf,ps}