# Projekt: 2
# Autor:   Michal Řezník
# Datum:   15.3.2022
SHELL = /usr/bin/env bash
NAME = proj2
LOGIN = xrezni28

all:
	pdflatex $(NAME).tex
	pdflatex $(NAME).tex

clean:
	rm -f $(NAME).{out,aux,dvi,log,pdf,ps}