# Generated by Django 3.2.9 on 2021-11-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='elo',
            field=models.IntegerField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
