# Generated by Django 3.2.9 on 2021-11-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_player_elo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='elo',
            field=models.IntegerField(default=200),
        ),
    ]
