// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShareRide.DAL;

#nullable disable

namespace ShareRide.DAL.Migrations
{
    [DbContext(typeof(ShareRideDbContext))]
    [Migration("20220602211637_RemoveAdress")]
    partial class RemoveAdress
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RideEntityUserEntity", b =>
                {
                    b.Property<Guid>("PassengerRidesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PassengersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PassengerRidesId", "PassengersId");

                    b.HasIndex("PassengersId");

                    b.ToTable("RideEntityUserEntity");
                });

            modelBuilder.Entity("ShareRide.DAL.Entities.CarEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CarType")
                        .HasColumnType("int");

                    b.Property<int>("Manufacturer")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PassengerSeats")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrationYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerGuid");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2dbd3cd2-ac74-45d0-9b47-8e268090e29b"),
                            CarType = 2,
                            Manufacturer = 48,
                            Name = "test name",
                            OwnerGuid = new Guid("1346f46f-f62c-471a-bbc6-3b5b7a514281"),
                            PassengerSeats = 4,
                            RegistrationYear = 2000
                        });
                });

            modelBuilder.Entity("ShareRide.DAL.Entities.RideEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DriverGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EstimatedEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Start")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("DriverGuid");

                    b.ToTable("Rides");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8cd12cb6-0de2-4fb9-8ffe-76f96967ab97"),
                            CarId = new Guid("2dbd3cd2-ac74-45d0-9b47-8e268090e29b"),
                            Destination = "Slavkov",
                            DriverGuid = new Guid("1346f46f-f62c-471a-bbc6-3b5b7a514281"),
                            EstimatedEndTime = new DateTime(2022, 4, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = "Brno",
                            StartTime = new DateTime(2022, 4, 10, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ShareRide.DAL.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1346f46f-f62c-471a-bbc6-3b5b7a514281"),
                            FirstName = "Adam",
                            LastName = "Kovacik"
                        });
                });

            modelBuilder.Entity("RideEntityUserEntity", b =>
                {
                    b.HasOne("ShareRide.DAL.Entities.RideEntity", null)
                        .WithMany()
                        .HasForeignKey("PassengerRidesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShareRide.DAL.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("PassengersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShareRide.DAL.Entities.CarEntity", b =>
                {
                    b.HasOne("ShareRide.DAL.Entities.UserEntity", "Owner")
                        .WithMany("OwnedCars")
                        .HasForeignKey("OwnerGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ShareRide.DAL.Entities.RideEntity", b =>
                {
                    b.HasOne("ShareRide.DAL.Entities.CarEntity", "Car")
                        .WithMany()
                        .HasForeignKey("CarId");

                    b.HasOne("ShareRide.DAL.Entities.UserEntity", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverGuid");

                    b.Navigation("Car");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("ShareRide.DAL.Entities.UserEntity", b =>
                {
                    b.Navigation("OwnedCars");
                });
#pragma warning restore 612, 618
        }
    }
}
